name: flutter_persistence
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  isar: 4.0.0-dev.14
  isar_flutter_libs: 4.0.0-dev.14
  path: ^1.8.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  word_generator: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
